# CUSTOMIZATION GUIDE FOR TASKS
# 1. Rename the task key (currently 'write_poem') to match your task's purpose
# 2. Craft a clear, specific 'description' of what the task does
# 3. Define an 'expected_output' that precisely describes the desired result
# 4. Ensure the 'agent' matches the agent defined in agents.yaml
# 5. Optional: Add more configuration parameters as needed
#    - context: Provide additional context for the task
#    - output_format: Specify the format of the output
#    - human_input: Require human input at a specific stage
#    - async_execution: Allow parallel task execution
# 6. Consider adding placeholders or variables for dynamic task configuration

# TODO: Replace 'write_poem' with a name that reflects your task's purpose
write_poem:
  # DESCRIPTION: Clearly explain what this task does
  description: >
    Write a poem about how CrewAI is awesome.
    Ensure the poem is engaging and adheres to the specified sentence count of {sentence_count}.

  # EXPECTED OUTPUT: Define exactly what the task should produce
  expected_output: >
    A beautifully crafted poem about CrewAI, with exactly {sentence_count} sentences.

  # AGENT: Link to the specific agent responsible for this task
  agent: poem_writer

  # Optional: Add more task-specific configurations
  # context: Additional context for the task
  # output_format: Specific format requirements
  # human_input: Require human intervention
  # async_execution: false
