topic_for_dummies_task:
  description: >
    Imagine you're a book publisher who has published a lot of books about a specific topic "For Dummies". 
    If I were writing a book called "{topic} for Dummies", what should the chapters be?
  expected_output: >
    A chapter outline for our book called "{topic} for Dummies". 
    Include chapter names and any subsection names that would be included in each chapter for the absolute best "For Dummies" book on {topic}.
  agent: keyword_researcher
  output_file: outputs/keyword_research/for_dummies.md

topic_conference_agenda_task:
  description: >
    Imagine you're a conference organizer who is planning a conference about {topic}. 
    If I were organizing a conference called "{topic} Conference", what should the agenda be?
  expected_output: >
    An agenda for our conference called "{topic} Conference". 
    Include talk titles and any other details that would be included in the conference agenda for the absolute best {topic} conference.
  agent: keyword_researcher
  output_file: outputs/keyword_research/conference_agenda.md

competitive_landscape_task:
  description: >
    Find the most popular websites about {topic}. Once you've found them, break out all of the things they write about into 5-15 high level categories.
    What are those categories? Give a brief description of each category, and a couple of specific examles of things they've written about that would fit into each category.
  expected_output: >
    A list of 5-15 high level categories about {topic}, with a brief description of each category, and a couple of specific examples of things the websites you've found have written about that would fit into each category.
  agent: keyword_researcher
  output_file: outputs/keyword_research/competitive_landscape.md

reddit_task:
  description: >
    What are the most popular subreddits about {topic} on Reddit? What are the most popular topics those subreddits talk about?
    What are some specific titles of popular threads on Reddit about {topic}? Make sure you're only searching for subreddits and threads about {topic}.
    Hint: use something like "{topic} site:reddit.com" in your search term
  expected_output: >
   A list of the most popular subreddits about {topic} on Reddit, with a list of the most popular topics those subreddits talk about.
   A list of some specific titles of popular threads on Reddit about {topic}. 
  agent: keyword_researcher
  output_file: outputs/keyword_research/reddit.md

add_keywords_to_state_task:
  description: >
    Based on all the previous research, create a list of keywords that we should target in our content.
    The keywords should be organized into a JSON array.
    Consider these categories:
    - Main keywords (e.g. "{topic}")
    - Related keywords (e.g. "{topic} tips", "{topic} guide")
    - Question keywords (e.g. "how to {topic}", "what is {topic}")
    - Long-tail keywords (e.g. "best {topic} for beginners", "advanced {topic} techniques")
    - Problem-solving keywords (e.g. "{topic} problems", "{topic} solutions")
    - Product-related keywords (e.g. "{topic} tools", "{topic} software")
    - Location-based keywords (e.g. "{topic} near me", "local {topic}")
    - Time-based keywords (e.g. "{topic} 2024", "{topic} trends")
    - Audience-specific keywords (e.g. "{topic} for beginners", "{topic} for experts")
    - Action-oriented keywords (e.g. "start {topic}", "learn {topic}")
    - Industry-specific keywords (e.g. "{topic} certification", "{topic} jobs")
    - Brand-related keywords (e.g. "{topic} brands", "best {topic} companies")
    
    For each category that makes sense for our topic, include at least 5 keywords.
    The keywords should be specific and targeted, not just generic variations.
    Include at least 50 keywords covering all aspects mentioned in the description.
    Do not include any text before or after the JSON array.
  expected_output: >
    Your output MUST be ONLY a valid JSON array of strings, with no additional text or explanation.
    Example format:
    ["keyword one", "keyword two", "keyword three"]
    
    Your final answer MUST include at least 50 keywords covering all aspects mentioned in the description.
    Do not include any text before or after the JSON array.
  agent: keyword_researcher
  output_file: outputs/keyword_research/keywords.md
