spoke_post_research_task:
  description: >
    Conduct detailed research for the post titled: {{spoke_post.title}}
    This post belongs to hub: {{spoke_post.hub}}
    
    Consider these keywords in your research: {{keywords}}
  expected_output: >
    An exhaustive report outlining the results of the research. Your output must be aligned with the post title and hub.
  agent: spoke_post_researcher

spoke_post_writer_task:
  description: >
    Write a blog post titled: {{spoke_post.title}}
    This post belongs to hub: {{spoke_post.hub}}
    
    Write a blog post of at least 3000 words that is SEO-optimized and engaging, using the research from the previous task. 
    Include any of these keywords in your post content, as long as they are relevant to the topic and used naturally in the context of the post: {{keywords}}
    
    Your complete blog post must include:
    - Title and description using SEO-optimized keywords for this post
    - At least 3 relevant FAQ questions and answers (in question-answer pairs), when appropriate for the post
  expected_output: >
    Post:
      title: str
      description: str
      content: str
      image: Optional[Image]
      faqs: Optional[List[FAQItem]]
  agent: spoke_post_writer

image_sourcing_task:
  description: >
    Using the Unsplash API, find and source a relevant primary image that represents the main theme or topic of this post.
    The image must be:
    - Relevant to the post topic
    - High quality and visually appealing
    - In landscape orientation (horizontal)
    - From Unsplash
  expected_output: >
    Image:
      src: str
      alt: str
      width: int
      height: int 
  agent: image_sourcing_expert

frontmatter_expert_task:
  description: >
    Generate a YAML frontmatter for the blog post titled: {{spoke_post.title}}
    This post belongs to hub: {{spoke_post.hub}}
    
    The frontmatter must strictly follow our frontmatter schema and include:
    - The post title and description
    - The hub slug
    - The image information from the previous task
    - Keywords from the post content (at least 5)
    - Featured status (default to false)
    - Draft status (default to true)
  expected_output: >
    Post:
      title: str
      description: str
      content: str
      image: Optional[Image]
      faqs: Optional[List[FAQItem]]
  agent: frontmatter_expert

content_approval_task:
  description: >
    Review and approve the final post content for: {{spoke_post.title}}
    This post belongs to hub: {{spoke_post.hub}}
    
    Your task:
    1. Review the post content for quality and completeness
    2. Format the post as a Markdown file with proper YAML frontmatter
    3. Save the file to: outputs/{{spoke_post.slug}}.md
    
    The output file MUST:
    1. Start with YAML frontmatter between --- delimiters
    2. Include all post metadata in the frontmatter
    3. Have the main content in Markdown format after the frontmatter

    After saving the file, confirm with:
    "✅ Successfully saved post to: outputs/{{spoke_post.slug}}.md"
  expected_output: >
    Post:
      title: str
      description: str
      content: str
      image: Optional[Image]
      faqs: Optional[List[FAQItem]]
  output_file: outputs/{{spoke_post.slug}}.md
  agent: content_approval_expert
